### PR TITLE
Client implementation

### PR DESCRIPTION
**Pull request by gzh**
Hi,

Wanted to share an implementation of client behavior within this library. It's not yet tested in production, but it's working in our test environment in a real project. Chances are that there'll be more changes to this codebase, but in its current state it still could be of use to someone.

### CODE REVIEW

**Comment by oberstet** [comment]
very cool. seems quite polished/professional work (I don't speak Haskell). not sure: currently, haskell-wamp is listed under "Libraries" (that is WAMP client impl.) only - not "Routers". https://wamp-proto.org/implementations.html#libraries
Is this still correct? Anything rgd specific WAMP features implemented & provided by this lib users should read there?

**Comment by gzh** [comment]
> very cool. seems quite polished/professional work (I don't speak Haskell). 

Thank you! 

>not sure: currently, haskell-wamp is listed under "Libraries" (that is WAMP client impl.) only - not "Routers". https://wamp-proto.org/implementations.html#libraries
> Is this still correct? Anything rgd specific WAMP features implemented & provided by this lib users should read there?

There is a Router implementation in this repo actually https://github.com/mulderr/haskell-wamp/blob/master/examples/warp-wamp-router/Main.hs , authored about 4 years ago. I haven't used or tested it, only compiled once and ran and saw it accepts connections.

Regarding this PR, -- as the matter of fact previously there were data types for WAMP messages and serialization methods within this repository, but not the higher-level implementation of a typical client, -- so this PR adds it.

On WAMP features implemented here - nothing special, just the very basic behavior expected from Caller, Callee, Publisher and Subscriber roles, as described in https://wamp-proto.org/_static/gen/wamp_latest_ietf.html#message-codes-and-direction. But that's still only the basic profile, for example no progressive call results, no call cancellations, no call timeouts. I wanted to get the core functionality working sooner.

**Comment by oberstet** [comment]
great! thanks for the info, background and such.  rgd the advanced vs basic features: no worries, this is "normal" - implementations can start with the "basic profile" of WAMP, which is supposed to be "easy" to realize. and then add advanced profile features if and when they feel so. and the BP is fully usable of course already. seems like that works for implementors, thanks for the details! kinda important for me at the WAMP community level ..

**Comment by mulderr** [comment]
Hi!

Looks like a bigger change. Do I understand correctly that this is still work in progress? If you'd like it merged here as is please shout and we can discuss details.

**Comment by gzh** [comment]
>  Do I understand correctly that this is still work in progress?

It's not that I currently have in mind anything which needs to be fixed or refactored (although of course this could be because I missed something). This code is not in production yet ;) but I've started to use it in a real project; so far for my use cases no further changes were necessary. From my standpoint, the changes to the client codebase are likely if fixes are required or if that'll be new features' implementation. I believe the API is sufficient for what it does and needs not to be changed.

> If you'd like it merged here as is please shout and we can discuss details.

It's totally up to you whether to merge it or not, -- we use stack and can build from my fork like we do it now. Of course I'd be glad to discuss what's going on in that PR, if required.

**Comment by oberstet** [comment]
@gzh closed? all that work - isn't that unfortunate? not sure, I have no clue, not even contributed to this project, but .. @mulderr opinions?

**Comment by gzh** [comment]
@oberstet Closed this one because it wasn't accepted for two months, and because more functionality is on its way -- I'm adding cryptosign authentication support. The sponsor of these latest changes will now decide how this is going to be published. Also, don't want to put everything into one PR, it's going to be too big.

**Comment by oberstet** [comment]
@gzh ahh, cool, thanks, good to hear! of course I would highly welcome if the sponsor decides to share your work as open source with the WAMP community in general;) also generally, I guess contributing to existing projects (this PR) is often preferred to a new/forked project ... but surely it depends, as there are different aspects and scenarios here. Just a general sidenote based on my experience ...

**Comment by gzh** [comment]
@oberstet Most likely this is what's going to happen, either a new PR or a new open fork/copy of the repo containing changes, -- it's just in this particular case this shouldn't be my decision. Guess you're right about the fork, sometimes it can let the contributors to keep the pace.

**Comment by mulderr** [comment]
@gzh Sorry, I missed the notifications on this but the code looked good in general. If, you decide to make a PR including the new stuff I'm sure we can get that merged. Cheers!

**Pull request closed without merging**
